
export const LOGIN_USER_FAILED = 'LOGIN_USER_FAILED';
export const LOGIN_SET_CREDENTIALS = 'LOGIN_SET_CREDENTIALS';
export const LOGOUT_USER = 'LOGOUT_USER';
export const REGISTER_USER = 'REGISTER_USER';